### ISSUE TITLE
AAU. I want to see the progression of the player's season through a graph.

### ISSUE THREAD

**Issue by andypham29** [karlogonzales/toplinebattle#1]
## Description
Display to the user a graph of the progression of points for each player.
Option of showing individual player or top line.

## Task
- [ ] Schedule a script to call data api and 
- [ ] Insert into a database the data from the script
- [ ] Display the data through a graph

**Comment by karlogonzales** [comment]
Attached is a javascript chart resource:
http://www.chartjs.org/

**Comment by karlogonzales** [comment]
Attached is a node schedule package:
https://www.npmjs.com/package/node-schedule

Alternatively, we can use a crontab to run a bash or python script to perform the same task.

**Comment by Songtone** [comment]
Hi guys!
